import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { appointments, crmDeals, crmPipelineStages, crmPipelines, customers, leads, tasks } from "@/db/schema";
import { getCurrentMembership } from "@/lib/auth/tenant";
import { hasPermission, PERMISSIONS, type Permission } from "@/lib/auth/permissions";
async function membershipFor(permission: Permission) { const membership = await getCurrentMembership(); return membership && hasPermission(membership.role, membership.permissions, permission) ? membership : null; }
export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) { const membership = await membershipFor(PERMISSIONS.RECEPTION_VIEW); if (!membership) return NextResponse.json({ error: "CRM access denied." }, { status: 403 }); const { id } = await context.params; const row = (await db.select({ deal: crmDeals, pipeline: crmPipelines, stage: crmPipelineStages, customer: customers, lead: leads }).from(crmDeals).innerJoin(crmPipelines, and(eq(crmPipelines.id, crmDeals.pipelineId), eq(crmPipelines.businessId, membership.businessId))).innerJoin(crmPipelineStages, and(eq(crmPipelineStages.id, crmDeals.stageId), eq(crmPipelineStages.businessId, membership.businessId))).leftJoin(customers, and(eq(customers.id, crmDeals.customerId), eq(customers.businessId, membership.businessId))).leftJoin(leads, and(eq(leads.id, crmDeals.leadId), eq(leads.businessId, membership.businessId))).where(and(eq(crmDeals.id, id), eq(crmDeals.businessId, membership.businessId))).limit(1))[0]; if (!row) return NextResponse.json({ error: "Deal not found." }, { status: 404 }); const [dealTasks, dealAppointments] = await Promise.all([db.select().from(tasks).where(and(eq(tasks.dealId, id), eq(tasks.businessId, membership.businessId))), db.select().from(appointments).where(and(eq(appointments.dealId, id), eq(appointments.businessId, membership.businessId)))]); return NextResponse.json({ ...row, tasks: dealTasks, appointments: dealAppointments }); }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { const membership = await membershipFor(PERMISSIONS.RECEPTION_MANAGE); if (!membership) return NextResponse.json({ error: "CRM management denied." }, { status: 403 }); const { id } = await context.params; const current = (await db.select().from(crmDeals).where(and(eq(crmDeals.id, id), eq(crmDeals.businessId, membership.businessId))).limit(1))[0]; if (!current) return NextResponse.json({ error: "Deal not found." }, { status: 404 }); const body = await request.json(); if (body.stageId) { const stage = (await db.select({ pipelineId: crmPipelineStages.pipelineId }).from(crmPipelineStages).where(and(eq(crmPipelineStages.id, String(body.stageId)), eq(crmPipelineStages.businessId, membership.businessId), eq(crmPipelineStages.pipelineId, current.pipelineId))).limit(1))[0]; if (!stage) return NextResponse.json({ error: "Invalid stage." }, { status: 400 }); } if (body.value !== undefined && body.value !== null && (Number.isNaN(Number(body.value)) || Number(body.value) < 0)) return NextResponse.json({ error: "Deal value must be non-negative." }, { status: 400 }); const status = ["open", "won", "lost"].includes(body.status) ? body.status : current.status; const now = new Date(); await db.update(crmDeals).set({ stageId: body.stageId || current.stageId, status, title: body.title === undefined ? current.title : String(body.title).trim(), value: body.value === undefined ? current.value : body.value, lossReason: body.lossReason === undefined ? current.lossReason : body.lossReason, updatedAt: now, actualCloseDate: ["won", "lost"].includes(status) && !current.actualCloseDate ? now : status === "open" ? null : current.actualCloseDate }).where(and(eq(crmDeals.id, id), eq(crmDeals.businessId, membership.businessId))); return NextResponse.json({ success: true }); }
