"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Source = { id: string; originalName: string; fileType: string; fileSize: number | null; status: string; createdAt: string; employeeId: string | null };
const documentTypes = new Set(["pdf", "word", "excel", "csv", "text"]);

export default function DocumentsPage() {
  const [sources, setSources] = useState<Source[]>([]); const [search, setSearch] = useState(""); const [type, setType] = useState("all"); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/ai/knowledge/sources", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load documents."); setSources((data.sources || []).filter((source: Source) => documentTypes.has(source.fileType))); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load documents.")); }, []);
  const filtered = useMemo(() => sources.filter((source) => (type === "all" || source.fileType === type) && (!search.trim() || source.originalName.toLowerCase().includes(search.toLowerCase()))), [sources, search, type]);
  return <main className="min-h-screen bg-[#07070A] px-6 py-10 text-white lg:px-10 lg:py-14"><div className="mx-auto max-w-[1400px]"><Link href="/dashboard/business-brain" className="text-xs text-white/40 hover:text-cyan-200">← Business Brain</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-300/70">Business Brain</p><h1 className="mt-3 text-4xl font-black">Documents</h1><p className="mt-3 text-sm text-white/40">Document-oriented view of your existing knowledge sources.</p></div><Link href="/dashboard/knowledge" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-black">Add document</Link></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search documents" className="flex-1 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm"/><select value={type} onChange={(event) => setType(event.target.value)} className="rounded-xl border border-white/10 bg-[#111116] px-4 py-3 text-sm"><option value="all">All document types</option>{[...new Set(sources.map((source) => source.fileType))].map((value) => <option key={value}>{value.toUpperCase()}</option>)}</select></div>{error ? <p className="mt-6 rounded-xl border border-red-400/20 p-4 text-red-200">{error}</p> : <section className="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-white/[0.025]">{filtered.length ? filtered.map((source) => <article key={source.id} className="grid gap-3 border-b border-white/[0.06] px-6 py-5 sm:grid-cols-[1fr_auto_auto]"><div><p className="font-bold">{source.originalName}</p><p className="mt-1 text-xs text-white/30">{source.employeeId ? "Employee-scoped" : "Shared with all AI employees"}</p></div><p className="text-sm text-white/45">{source.fileType.toUpperCase()} · {formatSize(source.fileSize)}</p><p className={source.status === "ready" ? "text-sm text-emerald-300" : source.status === "failed" ? "text-sm text-red-300" : "text-sm text-amber-200"}>{source.status}</p></article>) : <p className="p-12 text-center text-sm text-white/35">No documents match this view. Upload a supported PDF, Word, spreadsheet, CSV, or text file to begin.</p>}</section>}</div></main>;
}
function formatSize(value: number | null) { if (value == null) return "Size unavailable"; if (value < 1024) return `${value} B`; if (value < 1048576) return `${Math.round(value / 1024)} KB`; return `${(value / 1048576).toFixed(1)} MB`; }
