"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Business = { id: string; name: string; plan: string; billingProvider: string; subscriptionStatus: string; country: string | null; industry: string | null; activeEmployees: number; employees: number; conversations: number; voiceCalls: number; accountHealth: string; createdAt: string };

export default function AdminBusinessesPage() {
  const [rows, setRows] = useState<Business[]>([]); const [search, setSearch] = useState(""); const [plan, setPlan] = useState("all"); const [provider, setProvider] = useState("all"); const [status, setStatus] = useState("all"); const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { void fetch(`/api/admin/businesses?search=${encodeURIComponent(search)}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (response.ok) setRows(data.businesses || []); else setError(data.error || "Unable to load businesses."); }); }, 0); return () => window.clearTimeout(timer); }, [search]);
  const filtered = rows.filter((item) => (plan === "all" || item.plan === plan) && (provider === "all" || item.billingProvider === provider) && (status === "all" || item.subscriptionStatus === status));
  return <main className="min-h-screen bg-[#050507] px-4 py-8 text-white sm:px-6 lg:px-10 lg:py-12"><div className="mx-auto max-w-[1550px]"><Link href="/admin" className="text-xs font-semibold text-white/40 hover:text-cyan-300">← Admin</Link><header className="mt-5"><p className="text-xs font-bold uppercase tracking-[0.24em] text-cyan-300/70">Customer operations</p><h1 className="mt-3 text-4xl font-black">Business directory</h1><p className="mt-3 text-sm text-white/40">Search and filter tenant accounts using verified platform data.</p></header><div className="mt-6 flex flex-wrap gap-3"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, ID, country, industry" className="min-w-[260px] flex-1 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm" /><Filter value={plan} setValue={setPlan} options={["all", "starter", "growth", "pro", "enterprise"]} /><Filter value={provider} setValue={setProvider} options={["all", "stripe", "paystack", "internal", "legacy"]} /><Filter value={status} setValue={setStatus} options={["all", "active", "trialing", "past_due", "canceled", "legacy_no_subscription"]} /></div>{error && <p className="mt-5 rounded-xl border border-red-400/20 p-3 text-sm text-red-200">{error}</p>}<section className="mt-6 overflow-x-auto rounded-3xl border border-white/10 bg-white/[0.025]"><table className="w-full min-w-[1200px] text-left text-sm"><thead><tr className="border-b border-white/10 text-[10px] uppercase tracking-wider text-white/30"><th className="px-5 py-4">Business</th><th>Owner</th><th>Plan</th><th>Provider</th><th>Subscription</th><th>Employees</th><th>Conversations</th><th>Voice calls</th><th>Health</th><th>Created</th></tr></thead><tbody>{filtered.length ? filtered.map((business) => <tr key={business.id} className="border-b border-white/[0.06] text-white/65 hover:bg-white/[0.03]"><td className="px-5 py-4"><Link href={`/admin/businesses/${business.id}`} className="font-bold text-white/85 hover:text-cyan-300">{business.name}</Link><span className="block text-xs text-white/25">{business.id}</span></td><td className="text-white/40">Not available</td><td className="uppercase text-cyan-200">{business.plan}</td><td className="uppercase text-violet-200">{business.billingProvider}</td><td>{business.subscriptionStatus}</td><td>{business.activeEmployees} / {business.employees}</td><td>{business.conversations}</td><td>{business.voiceCalls}</td><td><span className={business.accountHealth === "Healthy" ? "text-emerald-300" : "text-amber-200"}>{business.accountHealth}</span></td><td className="text-white/35">{new Date(business.createdAt).toLocaleDateString()}</td></tr>) : <tr><td colSpan={10} className="px-5 py-12 text-center text-white/35">No businesses match these filters.</td></tr>}</tbody></table></section></div></main>;
}
function Filter({ value, setValue, options }: { value: string; setValue: (value: string) => void; options: string[] }) { return <select value={value} onChange={(event) => setValue(event.target.value)} className="rounded-xl border border-white/10 bg-[#111116] px-3 py-3 text-sm capitalize text-white/65">{options.map((option) => <option key={option} value={option}>{option === "all" ? "All" : option.replaceAll("_", " ")}</option>)}</select>; }
