import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { and, desc, eq, gte } from "drizzle-orm";
import { db } from "@/db";
import { actionApprovals, aiEmployeeActivities, aiEmployees, automationRuns, automations, auditLogs, businesses, businessUsers, conversations, integrations, messages, partnerOrganizations, partnerProducts, subscriptions, users } from "@/db/schema";
import { auth } from "@/lib/auth";
import { isPlatformAdmin } from "@/lib/auth/platform-admin";

export async function GET() {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (!await isPlatformAdmin(session.user.id)) return NextResponse.json({ error: "Platform admin access required." }, { status: 403 });
  const monthStart = new Date(); monthStart.setDate(1); monthStart.setHours(0, 0, 0, 0);
  const [businessesData, usersData, businessUsersData, employees, subscriptionsData, conversationsData, messagesData, automationsData, runs, integrationsData, activities, approvals, partners, products, events] = await Promise.all([
    db.select().from(businesses), db.select({ id: users.id }).from(users), db.select({ id: businessUsers.id }).from(businessUsers), db.select({ id: aiEmployees.id, businessId: aiEmployees.businessId, status: aiEmployees.status }).from(aiEmployees), db.select().from(subscriptions), db.select({ id: conversations.id, businessId: conversations.businessId, integrationId: conversations.integrationId }).from(conversations), db.select({ id: messages.id, businessId: messages.businessId, integrationId: messages.integrationId }).from(messages), db.select({ id: automations.id, businessId: automations.businessId }).from(automations), db.select({ id: automationRuns.id, businessId: automationRuns.businessId, status: automationRuns.status }).from(automationRuns), db.select({ id: integrations.id, businessId: integrations.businessId, status: integrations.status }).from(integrations), db.select({ id: aiEmployeeActivities.id, businessId: aiEmployeeActivities.businessId, type: aiEmployeeActivities.type, title: aiEmployeeActivities.title, description: aiEmployeeActivities.description, status: aiEmployeeActivities.status, createdAt: aiEmployeeActivities.createdAt }).from(aiEmployeeActivities).orderBy(desc(aiEmployeeActivities.createdAt)).limit(100), db.select({ id: actionApprovals.id, businessId: actionApprovals.businessId }).from(actionApprovals).where(eq(actionApprovals.status, "pending")), db.select({ id: partnerOrganizations.id, verificationStatus: partnerOrganizations.verificationStatus }).from(partnerOrganizations), db.select({ id: partnerProducts.id, status: partnerProducts.status }).from(partnerProducts), db.select({ id: auditLogs.id, businessId: auditLogs.businessId, action: auditLogs.action, description: auditLogs.description, createdAt: auditLogs.createdAt }).from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(30),
  ]);
  const current = subscriptionsData.filter((item) => ["active", "trialing", "enterprise_contract"].includes(item.status));
  const voice = conversationsData.filter((item) => item.integrationId === "voice-runtime");
  const summary = { totalBusinesses: businessesData.length, activeBusinesses: businessesData.filter((item) => item.status === "active").length, newBusinesses: businessesData.filter((item) => item.createdAt >= monthStart).length, registeredUsers: usersData.length, businessUsers: businessUsersData.length, totalEmployees: employees.length, activeEmployees: employees.filter((item) => item.status === "active").length, deployedEmployees: activities.filter((item) => item.type === "deployment_completed").length, voiceEnabledEmployees: activities.filter((item) => item.type === "voice.enabled").length, integrations: integrationsData.length, automations: automationsData.length, conversations: conversationsData.length, messages: messagesData.length, totalSubscriptions: subscriptionsData.length, activeSubscriptions: current.filter((item) => item.status === "active").length, trialingSubscriptions: subscriptionsData.filter((item) => item.status === "trialing").length, pastDueSubscriptions: subscriptionsData.filter((item) => item.status === "past_due").length, canceledSubscriptions: subscriptionsData.filter((item) => item.status === "canceled").length, starter: subscriptionsData.filter((item) => item.plan === "starter").length, growth: subscriptionsData.filter((item) => item.plan === "growth").length, pro: subscriptionsData.filter((item) => item.plan === "pro").length, enterprise: subscriptionsData.filter((item) => item.plan === "enterprise").length, legacy: businessesData.filter((business) => !subscriptionsData.some((item) => item.businessId === business.id)).length, paystack: subscriptionsData.filter((item) => item.provider === "paystack").length, stripe: subscriptionsData.filter((item) => item.provider === "stripe").length, manual: subscriptionsData.filter((item) => item.provider === "internal").length, voiceCalls: voice.length, voiceMinutes: "Not currently tracked", failedAutomations: runs.filter((item) => item.status === "failed").length, aiFailures: activities.filter((item) => item.status === "failed").length, integrationFailures: integrationsData.filter((item) => item.status === "error" || item.status === "failed").length, escalations: activities.filter((item) => item.type.includes("escalat")).length, pendingApprovals: approvals.length, pausedEmployees: employees.filter((item) => item.status !== "active").length, billingAttention: subscriptionsData.filter((item) => item.status === "past_due").length };
  return NextResponse.json({ summary, commercial: { revenue: "Revenue reporting not yet available." }, partners: { total: partners.length, verified: partners.filter((item) => item.verificationStatus === "verified").length, pending: partners.filter((item) => item.verificationStatus === "pending_verification").length, products: products.length, submittedProducts: products.filter((item) => item.status === "submitted").length, underReview: products.filter((item) => item.status === "under_review").length, published: products.filter((item) => item.status === "published").length } , events, activities: activities.slice(0, 20) });
}
