"use client";

import { useState } from "react";
import { authClient } from "@/lib/auth-client";

export default function AccountSecurity({ name, email }: { name: string; email: string }) {
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [newEmail, setNewEmail] = useState(""); const [passwordMessage, setPasswordMessage] = useState(""); const [emailMessage, setEmailMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function changePassword() { setError(""); setPasswordMessage(""); if (newPassword.length < 8) { setError("New password must be at least 8 characters."); return; } if (newPassword !== confirmPassword) { setError("New passwords do not match."); return; } setLoading(true); const result = await authClient.changePassword({ currentPassword, newPassword, revokeOtherSessions: true }); if (result.error) setError(result.error.message || "Unable to change password."); else { setPasswordMessage("Password changed successfully."); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); } setLoading(false); }
  async function changeEmail() { setError(""); setEmailMessage(""); const value = newEmail.trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) { setError("Enter a valid new email address."); return; } setLoading(true); const result = await authClient.changeEmail({ newEmail: value, callbackURL: "/dashboard/settings" }); if (result.error) setError(result.error.message || "Unable to request email change."); else { setEmailMessage("Email change requested. Check the new address for verification."); setNewEmail(""); } setLoading(false); }
  return <section className="mt-6 rounded-2xl border border-white/[0.08] bg-white/[0.03] p-6 shadow-2xl"><p className="text-sm font-medium text-violet-400">Account security</p><h2 className="mt-2 text-lg font-semibold">{name}</h2><p className="mt-1 text-sm text-white/45">Current login email: {email}</p><div className="mt-7 grid gap-8 lg:grid-cols-2"><div><h3 className="font-semibold">Change password</h3><div className="mt-4 space-y-3"><Password label="Current password" value={currentPassword} onChange={setCurrentPassword} /><Password label="New password" value={newPassword} onChange={setNewPassword} /><Password label="Confirm new password" value={confirmPassword} onChange={setConfirmPassword} /><button type="button" onClick={() => void changePassword()} disabled={loading} className="rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{loading ? "Changing..." : "Change password"}</button></div></div><div><h3 className="font-semibold">Change login email</h3><p className="mt-2 text-sm leading-6 text-white/40">Changing your login email may require verification.</p><input type="email" value={newEmail} onChange={(event) => setNewEmail(event.target.value)} placeholder="new-address@example.com" className="mt-4 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm" /><button type="button" onClick={() => void changeEmail()} disabled={loading} className="mt-3 rounded-xl border border-cyan-300/25 bg-cyan-300/[0.06] px-4 py-3 text-sm font-semibold text-cyan-200 disabled:opacity-50">Request email change</button></div></div>{passwordMessage && <p className="mt-5 text-sm text-emerald-200">{passwordMessage}</p>}{emailMessage && <p className="mt-2 text-sm text-emerald-200">{emailMessage}</p>}{error && <p className="mt-5 rounded-xl border border-red-400/20 bg-red-400/[0.05] p-3 text-sm text-red-200">{error}</p>}</section>;
}
function Password({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm text-white/65">{label}<input type="password" value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm" /></label>; }
