import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { db } from "@/db";
import { marketingContentItems } from "@/db/schema";
import { requireMarketingAccess } from "@/lib/marketing/context";
import { marketingCampaignBelongsToBusiness } from "@/lib/marketing/ownership";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { const access = await requireMarketingAccess("view"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const { id } = await params; const [content] = await db.select().from(marketingContentItems).where(and(eq(marketingContentItems.id, id), eq(marketingContentItems.businessId, access.businessId))); if (!content) return NextResponse.json({ error: "Content not found." }, { status: 404 }); return NextResponse.json({ content }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const access = await requireMarketingAccess("manage"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const { id } = await params; const body = await request.json().catch(() => null); if (body && "campaignId" in body && body.campaignId !== null) { if (typeof body.campaignId !== "string") return NextResponse.json({ error: "campaignId must be a string or null." }, { status: 400 }); if (!(await marketingCampaignBelongsToBusiness(access.businessId, body.campaignId))) return NextResponse.json({ error: "Campaign does not belong to this business." }, { status: 403 }); } if (body && "approvalStatus" in body) return NextResponse.json({ error: "Content approval status is controlled by the Marketing approval workflow." }, { status: 409 }); const patch: Record<string, unknown> = {}; for (const key of ["title", "contentType", "brief", "status", "campaignId"]) if (body && key in body) patch[key] = body[key]; patch.updatedAt = new Date(); const result = await db.update(marketingContentItems).set(patch).where(and(eq(marketingContentItems.id, id), eq(marketingContentItems.businessId, access.businessId))); if (result.rowsAffected === 0) return NextResponse.json({ error: "Content not found." }, { status: 404 }); return GET(request, { params }); }
