"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

const objectives = ["awareness", "engagement", "lead_generation", "conversion", "retention", "reactivation", "product_launch", "promotion", "traffic", "other"];
const channels = ["facebook", "instagram", "linkedin", "x", "tiktok", "youtube", "telegram", "website", "email", "whatsapp"];

export default function NewMarketingCampaignPage() {
  const router = useRouter(); const [step, setStep] = useState(0); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", description: "", campaignType: "organic", objective: "awareness", offer: "", landingUrl: "", timezone: "UTC", channels: [] as string[], startAt: "", endAt: "" });
  const update = (key: string, value: string | string[]) => setForm((current) => ({ ...current, [key]: value }));
  async function create() { setSaving(true); setError(""); const response = await fetch("/api/marketing/campaigns", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); setSaving(false); if (!response.ok) { setError(body.error || "Unable to create campaign."); return; } router.push(`/dashboard/marketing/campaigns/${body.campaign.id}`); }
  const labels = ["Basics", "Objective", "Audience", "Offer", "Channels", "Schedule", "Content plan", "Approval", "Tracking", "Review"];
  return <main className="min-h-screen bg-surface-page px-4 py-8 text-white sm:px-6 lg:px-10 lg:py-12"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-300/70">Kuba Marketing</p><h1 className="mt-3 text-4xl font-black">Create campaign</h1><div className="mt-8 grid gap-2 sm:grid-cols-5 lg:grid-cols-10">{labels.map((label, index) => <button key={label} type="button" onClick={() => setStep(index)} className={`rounded-control px-2 py-2 text-xs font-semibold ${index === step ? "bg-cyan-400 text-slate-950" : "bg-surface-card text-text-tertiary"}`}>{index + 1}. {label}</button>)}</div><section className="mt-6 rounded-card border border-border-default bg-surface-card p-6"><Step step={step} form={form} update={update} channels={channels} objectives={objectives} />{error && <p className="mt-4 text-sm text-danger">{error}</p>}<div className="mt-8 flex justify-between"><button type="button" disabled={step === 0} onClick={() => setStep((value) => Math.max(0, value - 1))} className="rounded-control border border-border-default px-4 py-2 text-sm disabled:opacity-40">Back</button>{step === labels.length - 1 ? <button type="button" onClick={create} disabled={saving || !form.name.trim()} className="rounded-control bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-50">{saving ? "Creating…" : "Create draft"}</button> : <button type="button" onClick={() => setStep((value) => Math.min(labels.length - 1, value + 1))} className="rounded-control bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950">Continue</button>}</div></section></div></main>;
}

type CampaignForm = { name: string; description: string; campaignType: string; objective: string; offer: string; landingUrl: string; timezone: string; channels: string[]; startAt: string; endAt: string };
function Step({ step, form, update, channels, objectives }: { step: number; form: CampaignForm; update: (key: string, value: string | string[]) => void; channels: string[]; objectives: string[] }) {
  if (step === 0) return <Fields title="Campaign basics"><Field label="Name" value={form.name} onChange={(value) => update("name", value)} placeholder="e.g. Spring lead generation" /><Field label="Description" value={form.description} onChange={(value) => update("description", value)} placeholder="What should this campaign achieve?" /><Field label="Campaign type" value={form.campaignType} onChange={(value) => update("campaignType", value)} placeholder="organic" /></Fields>;
  if (step === 1) return <Fields title="Objective"><div className="grid gap-3 sm:grid-cols-2">{objectives.map((objective) => <button type="button" key={objective} onClick={() => update("objective", objective)} className={`rounded-control border px-4 py-3 text-left text-sm ${form.objective === objective ? "border-cyan-300 bg-cyan-400/10 text-cyan-200" : "border-border-muted"}`}>{objective.replaceAll("_", " ")}</button>)}</div></Fields>;
  if (step === 2) return <Fields title="Audience"><p className="text-sm text-text-tertiary">Choose an existing audience after creating this draft, or continue without one. Audience rules remain tenant-scoped.</p></Fields>;
  if (step === 3) return <Fields title="Offer and landing page"><Field label="Approved offer or product" value={form.offer} onChange={(value) => update("offer", value)} placeholder="Use approved Business Brain facts only" /><Field label="Landing URL" value={form.landingUrl} onChange={(value) => update("landingUrl", value)} placeholder="https://…" /></Fields>;
  if (step === 4) return <Fields title="Planning channels"><div className="grid gap-3 sm:grid-cols-2">{channels.map((channel) => <label key={channel} className="flex items-center gap-3 rounded-control border border-border-muted px-4 py-3 text-sm"><input type="checkbox" checked={form.channels.includes(channel)} onChange={(event) => update("channels", event.target.checked ? [...form.channels, channel] : form.channels.filter((value: string) => value !== channel))} />{channel}</label>)}</div><p className="mt-4 text-xs text-text-muted">Channels are planning targets. Provider execution is not connected.</p></Fields>;
  if (step === 5) return <Fields title="Schedule"><Field label="Timezone" value={form.timezone} onChange={(value) => update("timezone", value)} placeholder="UTC" /><Field label="Start" value={form.startAt} onChange={(value) => update("startAt", value)} placeholder="2026-10-01T09:00" /><Field label="End" value={form.endAt} onChange={(value) => update("endAt", value)} placeholder="2026-10-31T18:00" /></Fields>;
  return <Fields title={step === 6 ? "Content plan" : step === 7 ? "Approval" : step === 8 ? "Tracking" : "Review"}><p className="text-sm leading-6 text-text-tertiary">{step === 6 ? "Create separate channel variants in Content Studio after saving this draft." : step === 7 ? "Content and campaigns remain drafts until a permitted reviewer approves them." : step === 8 ? "UTM fields and attribution can be added after the draft is created." : `Review ${form.name || "your campaign"} before creating the native draft.`}</p></Fields>;
}
function Fields({ title, children }: { title: string; children: React.ReactNode }) { return <div><h2 className="text-xl font-bold">{title}</h2><div className="mt-5 space-y-4">{children}</div></div>; }
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block text-sm font-semibold">{label}<input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-control border border-border-muted bg-surface-page px-3 py-2.5 text-sm font-normal text-white outline-none focus:border-cyan-300" /></label>; }
