import { and, desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { db } from "@/db";
import { crmDeals, customers, leads, marketingAttributions, marketingCampaigns } from "@/db/schema";
import { requireMarketingAccess } from "@/lib/marketing/context";

export async function GET() { const access = await requireMarketingAccess("view"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); return NextResponse.json({ attributions: await db.select().from(marketingAttributions).where(eq(marketingAttributions.businessId, access.businessId)).orderBy(desc(marketingAttributions.occurredAt)) }); }
export async function POST(request: Request) { const access = await requireMarketingAccess("manage"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const body = await request.json().catch(() => null); if (typeof body?.campaignId !== "string" || typeof body?.eventType !== "string") return NextResponse.json({ error: "campaignId and eventType are required." }, { status: 400 }); const [campaign] = await db.select({ id: marketingCampaigns.id }).from(marketingCampaigns).where(and(eq(marketingCampaigns.id, body.campaignId), eq(marketingCampaigns.businessId, access.businessId))); if (!campaign) return NextResponse.json({ error: "Campaign does not belong to this business." }, { status: 403 }); const refs = [{ id: body?.leadId, table: leads, label: "Lead" }, { id: body?.customerId, table: customers, label: "Customer" }, { id: body?.dealId, table: crmDeals, label: "Deal" }]; for (const ref of refs) { if (!ref.id) continue; const [row] = await db.select({ id: ref.table.id }).from(ref.table).where(and(eq(ref.table.id, ref.id), eq(ref.table.businessId, access.businessId))); if (!row) return NextResponse.json({ error: `${ref.label} does not belong to this business.` }, { status: 403 }); } const duplicate = await db.select({ id: marketingAttributions.id }).from(marketingAttributions).where(and(eq(marketingAttributions.businessId, access.businessId), eq(marketingAttributions.campaignId, body.campaignId), eq(marketingAttributions.eventType, body.eventType), body?.leadId ? eq(marketingAttributions.leadId, body.leadId) : eq(marketingAttributions.leadId, "__none__"), body?.customerId ? eq(marketingAttributions.customerId, body.customerId) : eq(marketingAttributions.customerId, "__none__"), body?.dealId ? eq(marketingAttributions.dealId, body.dealId) : eq(marketingAttributions.dealId, "__none__"))).limit(1); if (duplicate.length) return NextResponse.json({ error: "Equivalent attribution already exists.", code: "DUPLICATE_ATTRIBUTION" }, { status: 409 }); const now = new Date(); const attribution = { id: randomUUID(), businessId: access.businessId, campaignId: body.campaignId, customerId: typeof body?.customerId === "string" ? body.customerId : null, leadId: typeof body?.leadId === "string" ? body.leadId : null, dealId: typeof body?.dealId === "string" ? body.dealId : null, eventType: body.eventType, occurredAt: body?.occurredAt ? new Date(body.occurredAt) : now, value: typeof body?.value === "number" ? body.value : null, currency: typeof body?.currency === "string" ? body.currency : null, metadata: null, createdAt: now }; await db.insert(marketingAttributions).values(attribution); return NextResponse.json({ attribution }, { status: 201 }); }
