"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import LoadingState from "../../components/ui/LoadingState";
import ErrorState from "../../components/ui/ErrorState";

type Conversation = { id: string; customerName: string; channel: string; lastMessage: string; lastMessageAt: string; status: string; priority: string; needsHuman: boolean; assignedEmployee: { name: string } | null; assignedUser: { name: string } | null };
export default function ConversationsPage() {
  const [items, setItems] = useState<Conversation[]>([]); const [search, setSearch] = useState(""); const [channel, setChannel] = useState("all"); const [status, setStatus] = useState("all"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { void fetch("/api/inbox/workspace", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load conversations."); setItems(data.conversations || []); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load conversations.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => items.filter((item) => { const query = search.toLowerCase().trim(); return (!query || [item.customerName, item.lastMessage, item.channel].some((value) => value.toLowerCase().includes(query))) && (channel === "all" || item.channel === channel) && (status === "all" || item.status === status); }), [items, search, channel, status]);
  return <main className="min-h-screen bg-[#050507] px-6 py-10 text-white lg:px-10 lg:py-14"><div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-300/70">Customer Operations</p><h1 className="mt-3 text-4xl font-black">Conversations</h1><p className="mt-3 text-sm text-white/40">Search and triage every selected-business conversation.</p></div><Link href="/dashboard/inbox" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-black">Open unified inbox</Link></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search customer or message" className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm"/><select value={channel} onChange={(event) => setChannel(event.target.value)} className="rounded-xl border border-white/10 bg-[#111116] px-4 py-3 text-sm"><option value="all">All channels</option>{[...new Set(items.map((item) => item.channel))].map((value) => <option key={value}>{value}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-white/10 bg-[#111116] px-4 py-3 text-sm"><option value="all">All statuses</option>{[...new Set(items.map((item) => item.status))].map((value) => <option key={value}>{value}</option>)}</select></div>{error ? <div className="mt-6"><ErrorState variant="inline" message={error} /></div> : loading ? <div className="mt-6"><LoadingState variant="panel" message="Loading conversations..." /></div> : <section className="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-white/[0.025]">{filtered.length ? filtered.map((item) => <Link key={item.id} href={`/dashboard/inbox?conversation=${encodeURIComponent(item.id)}`} className="grid gap-3 border-b border-white/[0.06] px-6 py-5 hover:bg-white/[0.03] lg:grid-cols-[1.2fr_1fr_1fr_auto]"><div><p className="font-bold">{item.customerName}</p><p className="mt-1 truncate text-xs text-white/35">{item.lastMessage}</p></div><p className="text-sm text-white/50">{item.channel} · {item.status}</p><p className="text-sm text-white/50">{item.assignedUser?.name || item.assignedEmployee?.name || "Unassigned"}</p><span className={item.needsHuman ? "text-sm text-amber-200" : "text-sm text-cyan-200"}>{item.needsHuman ? "Needs human" : item.priority}</span></Link>) : <p className="p-12 text-center text-sm text-white/35">No conversations match these filters.</p>}</section>}</div></main>;
}
