import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { businesses, subscriptions, aiEmployees, conversations } from "@/db/schema";
import { auth } from "@/lib/auth";
import { isPlatformAdmin } from "@/lib/auth/platform-admin";

export async function GET(request: Request) { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (!await isPlatformAdmin(session.user.id)) return NextResponse.json({ error: "Platform admin access required." }, { status: 403 }); const params = new URL(request.url).searchParams; const search = params.get("search")?.toLowerCase() || ""; const [businessRows, subscriptionsData, employeeRows, conversationRows] = await Promise.all([db.select().from(businesses), db.select({ businessId: subscriptions.businessId, provider: subscriptions.provider, plan: subscriptions.plan, status: subscriptions.status, trialEnd: subscriptions.trialEnd }).from(subscriptions), db.select({ businessId: aiEmployees.businessId, status: aiEmployees.status }).from(aiEmployees), db.select({ businessId: conversations.businessId, integrationId: conversations.integrationId }).from(conversations)]); const rows = businessRows.filter((item) => !search || `${item.name} ${item.id} ${item.country || ""} ${item.industry || ""}`.toLowerCase().includes(search)).map((item) => { const subscription = subscriptionsData.find((entry) => entry.businessId === item.id); const employeeRowsForBusiness = employeeRows.filter((employee) => employee.businessId === item.id); const voice = conversationRows.filter((conversation) => conversation.businessId === item.id && conversation.integrationId === "voice-runtime"); return { ...item, plan: subscription?.plan || item.plan, billingProvider: subscription?.provider || "legacy", subscriptionStatus: subscription?.status || "legacy_no_subscription", trialEnd: subscription?.trialEnd || null, activeEmployees: employeeRowsForBusiness.filter((employee) => employee.status === "active").length, employees: employeeRowsForBusiness.length, conversations: conversationRows.filter((conversation) => conversation.businessId === item.id).length, voiceCalls: voice.length, accountHealth: subscription?.status === "past_due" ? "Billing attention" : employeeRowsForBusiness.length === 0 ? "Needs setup" : "Healthy" }; }); return NextResponse.json({ businesses: rows }); }
