"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Call = { id: string; customer: string; phoneNumber: string; employee: string; status: string; startedAt: string; updatedAt: string };

export default function LiveCallsPage() {
  const [calls, setCalls] = useState<Call[]>([]);
  const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/workforce/live-calls", { cache: "no-store" }); const data = await response.json(); if (!response.ok) setError(data.error || "Unable to load live calls."); else setCalls(data.calls || []); }
  useEffect(() => { const initial = window.setTimeout(() => { void load(); }, 0); const timer = window.setInterval(() => void load(), 10000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, []);
  async function action(conversationId: string, actionName: "transfer" | "end") { await fetch("/api/workforce/live-calls", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ conversationId, action: actionName }) }); await load(); }
  return <main className="min-h-screen bg-[#07070A] px-4 py-8 text-white sm:px-6 lg:px-8 lg:py-12"><div className="mx-auto max-w-7xl"><Link href="/dashboard/workforce" className="text-xs font-semibold text-white/40 hover:text-cyan-300">← Workforce</Link><header className="mt-5"><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-300/70">Voice operations</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em]">Live calls</h1><p className="mt-3 text-sm text-white/40">Monitor active voice conversations through the existing inbox and handoff system.</p></header>{error && <p className="mt-6 rounded-xl border border-red-400/20 p-3 text-sm text-red-200">{error}</p>}<section className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-white/[0.025]"><div className="grid grid-cols-5 gap-4 border-b border-white/10 px-5 py-4 text-[10px] font-bold uppercase tracking-[0.18em] text-white/30"><span>Customer</span><span>AI employee</span><span>Phone</span><span>Status</span><span>Actions</span></div>{calls.length ? calls.map((call) => <div key={call.id} className="grid grid-cols-5 items-center gap-4 border-b border-white/[0.06] px-5 py-5 text-sm"><div><p className="font-semibold text-white/80">{call.customer}</p><p className="mt-1 text-xs text-white/30">{new Date(call.startedAt).toLocaleTimeString()}</p></div><span className="text-white/60">{call.employee}</span><span className="text-white/50">{call.phoneNumber || "Unknown"}</span><span className="rounded-full border border-cyan-300/20 bg-cyan-300/[0.07] px-2 py-1 text-center text-xs text-cyan-200">{call.status}</span><div className="flex gap-2"><Link href={`/dashboard/inbox?conversation=${call.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60">View</Link><button type="button" onClick={() => void action(call.id, "transfer")} className="rounded-lg border border-amber-300/20 px-3 py-2 text-xs text-amber-200">Transfer</button><button type="button" onClick={() => void action(call.id, "end")} className="rounded-lg border border-red-300/20 px-3 py-2 text-xs text-red-200">End</button></div></div>) : <p className="px-5 py-12 text-center text-sm text-white/35">No active voice conversations.</p>}</section></div></main>;
}