"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

const types = ["post", "story", "reel", "short_video", "long_video", "email", "ad_copy", "article", "graphic", "carousel", "other"];
export default function NewMarketingContentPage() {
  const router = useRouter(); const [form, setForm] = useState({ title: "", brief: "", contentType: "post", campaignId: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  function update(key: keyof typeof form, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/marketing/content", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); setSaving(false); if (!response.ok) { setError(body.error || "Unable to create content."); return; } router.push(`/dashboard/marketing/content/${body.content.id}`); }
  return <main className="min-h-screen bg-surface-page px-4 py-8 text-white sm:px-6 lg:px-10"><div className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-300/70">Kuba Marketing · Content Studio</p><h1 className="mt-3 text-4xl font-black">Create content</h1><p className="mt-3 text-sm text-text-tertiary">Start a tenant-scoped draft. Channel variants and approvals can be added after saving.</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-card border border-border-default bg-surface-card p-6"><label className="block text-sm font-semibold">Title<input required value={form.title} onChange={(e) => update("title", e.target.value)} className="mt-2 w-full rounded-control border border-border-muted bg-surface-page px-3 py-2.5 font-normal outline-none focus:border-cyan-300" /></label><label className="block text-sm font-semibold">Brief<textarea value={form.brief} onChange={(e) => update("brief", e.target.value)} rows={5} className="mt-2 w-full rounded-control border border-border-muted bg-surface-page px-3 py-2.5 font-normal outline-none focus:border-cyan-300" /></label><label className="block text-sm font-semibold">Content type<select value={form.contentType} onChange={(e) => update("contentType", e.target.value)} className="mt-2 w-full rounded-control border border-border-muted bg-surface-page px-3 py-2.5 font-normal"><option value="">Select type</option>{types.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label className="block text-sm font-semibold">Campaign ID <span className="font-normal text-text-muted">(optional)</span><input value={form.campaignId} onChange={(e) => update("campaignId", e.target.value)} placeholder="Paste an existing campaign ID" className="mt-2 w-full rounded-control border border-border-muted bg-surface-page px-3 py-2.5 font-normal outline-none focus:border-cyan-300" /></label>{error && <p className="text-sm text-danger">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="rounded-control border border-border-muted px-4 py-2.5 text-sm">Cancel</button><button type="submit" disabled={saving} className="rounded-control bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 disabled:opacity-50">{saving ? "Saving…" : "Save draft"}</button></div></form></div></main>;
}
