import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { crmDeals, leads } from "@/db/schema";
import { getCurrentMembership } from "@/lib/auth/tenant";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
export async function GET(request: Request) {
 const membership = await getCurrentMembership(); if (!membership || !hasPermission(membership.role, membership.permissions, PERMISSIONS.CRM_VIEW)) return NextResponse.json({ error: "CRM access denied." }, { status: 403 });
 const p = new URL(request.url).searchParams; const all = await db.select().from(crmDeals).where(eq(crmDeals.businessId, membership.businessId)); const leadRows = await db.select().from(leads).where(eq(leads.businessId, membership.businessId)); const from = p.get("from") ? new Date(p.get("from")!) : null; const to = p.get("to") ? new Date(p.get("to")!) : null; const deals = all.filter((d) => (!from || new Date(d.createdAt) >= from) && (!to || new Date(d.createdAt) <= to)); const open = deals.filter((d) => d.status === "open"); const won = deals.filter((d) => d.status === "won"); const lost = deals.filter((d) => d.status === "lost"); const currencies = [...new Set(open.map((d) => d.currency || "GHS"))]; const grouped = Object.fromEntries(currencies.map((currency) => [currency, open.filter((d) => (d.currency || "GHS") === currency).reduce((sum, d) => sum + (Number(d.value) || 0), 0)])); const converted = leadRows.filter((l) => Boolean(l.closedAt || l.dealStatus === "won"));
 return NextResponse.json({ totalDeals: deals.length, openDeals: open.length, wonDeals: won.length, lostDeals: lost.length, openValueByCurrency: grouped, wonValueByCurrency: Object.fromEntries([...new Set(won.map((d) => d.currency || "GHS"))].map((c) => [c, won.filter((d) => (d.currency || "GHS") === c).reduce((s, d) => s + (Number(d.value) || 0), 0)])), winRate: deals.length ? won.length / deals.length : 0, leadCount: leadRows.length, conversionCount: converted.length, leadConversionRate: leadRows.length ? converted.length / leadRows.length : 0, stageDistribution: (Object.values(Object.groupBy(deals, (d) => `${d.pipelineId}:${d.stageId}`)) as (typeof deals)[]).map((rows) => ({ pipelineId: rows[0].pipelineId, stageId: rows[0].stageId, dealCount: rows.length, openCount: rows.filter((d) => d.status === "open").length })), sourceBreakdown: (Object.values(Object.groupBy(deals, (d) => d.source || "unknown")) as (typeof deals)[]).map((rows) => ({ source: rows[0].source || "unknown", dealCount: rows.length, wonDeals: rows.filter((d) => d.status === "won").length })), expectedClose: { overdueOpen: open.filter((d) => d.expectedCloseDate && new Date(d.expectedCloseDate) < new Date()).length, noDate: open.filter((d) => !d.expectedCloseDate).length }, dateRange: { from: p.get("from"), to: p.get("to") } });
}
