import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { db } from "@/db";
import { marketingCampaigns } from "@/db/schema";
import { requireMarketingAccess } from "@/lib/marketing/context";
import { assertCampaignTransition } from "@/lib/marketing/lifecycle";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { const access = await requireMarketingAccess("view"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const { id } = await params; const [campaign] = await db.select().from(marketingCampaigns).where(and(eq(marketingCampaigns.id, id), eq(marketingCampaigns.businessId, access.businessId))); if (!campaign) return NextResponse.json({ error: "Campaign not found." }, { status: 404 }); return NextResponse.json({ campaign }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const access = await requireMarketingAccess("manage"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const { id } = await params; const body = await request.json().catch(() => null); const [current] = await db.select().from(marketingCampaigns).where(and(eq(marketingCampaigns.id, id), eq(marketingCampaigns.businessId, access.businessId))); if (!current) return NextResponse.json({ error: "Campaign not found." }, { status: 404 }); const allowed = ["name", "description", "objective", "campaignType", "targetAudienceId", "offer", "landingUrl", "timezone", "approvalStatus"] as const; const patch: Record<string, unknown> = Object.fromEntries(allowed.filter((key) => body && key in body).map((key) => [key, body[key]])); if (body && typeof body.status === "string") { try { assertCampaignTransition(current.status, body.status); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Invalid campaign transition." }, { status: 409 }); } patch.status = body.status; } patch.updatedAt = new Date(); await db.update(marketingCampaigns).set(patch).where(and(eq(marketingCampaigns.id, id), eq(marketingCampaigns.businessId, access.businessId))); return GET(request, { params }); }
