import { NextResponse } from "next/server";
import { and, desc, eq } from "drizzle-orm";
import { db } from "@/db";
import { crmDeals, crmPipelineStages, crmPipelines } from "@/db/schema";
import { getCurrentMembership } from "@/lib/auth/tenant";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";

async function access() { const membership = await getCurrentMembership(); if (!membership || !hasPermission(membership.role, membership.permissions, PERMISSIONS.RECEPTION_VIEW)) return null; return membership; }
export async function GET(request: Request) { const membership = await access(); if (!membership) return NextResponse.json({ error: "CRM access denied." }, { status: 403 }); const q = new URL(request.url).searchParams.get("q")?.trim().toLowerCase(); const rows = await db.select({ deal: crmDeals, pipeline: crmPipelines, stage: crmPipelineStages }).from(crmDeals).innerJoin(crmPipelines, and(eq(crmPipelines.id, crmDeals.pipelineId), eq(crmPipelines.businessId, membership.businessId))).innerJoin(crmPipelineStages, and(eq(crmPipelineStages.id, crmDeals.stageId), eq(crmPipelineStages.businessId, membership.businessId))).where(eq(crmDeals.businessId, membership.businessId)).orderBy(desc(crmDeals.updatedAt)); return NextResponse.json({ deals: rows.filter((row) => !q || `${row.deal.title} ${row.deal.description || ""}`.toLowerCase().includes(q)).map((row) => ({ ...row.deal, pipelineName: row.pipeline.name, stageName: row.stage.name })) }); }
export async function POST(request: Request) { const membership = await access(); if (!membership || !hasPermission(membership.role, membership.permissions, PERMISSIONS.RECEPTION_MANAGE)) return NextResponse.json({ error: "CRM management denied." }, { status: 403 }); const body = await request.json(); const title = String(body.title || "").trim(); if (!title || !body.pipelineId || !body.stageId) return NextResponse.json({ error: "title, pipelineId, and stageId are required." }, { status: 400 }); const valid = await db.select({ pipelineId: crmPipelineStages.pipelineId }).from(crmPipelineStages).innerJoin(crmPipelines, and(eq(crmPipelines.id, crmPipelineStages.pipelineId), eq(crmPipelines.businessId, membership.businessId))).where(and(eq(crmPipelineStages.id, body.stageId), eq(crmPipelineStages.pipelineId, body.pipelineId), eq(crmPipelineStages.businessId, membership.businessId))).limit(1); if (!valid[0]) return NextResponse.json({ error: "Stage does not belong to this pipeline." }, { status: 400 }); const now = new Date(); const id = crypto.randomUUID(); await db.insert(crmDeals).values({ id, businessId: membership.businessId, customerId: body.customerId || null, leadId: body.leadId || null, title, description: body.description || null, pipelineId: body.pipelineId, stageId: body.stageId, assignedEmployeeId: body.assignedEmployeeId || null, assignedUserId: body.assignedUserId || null, status: body.status || "open", value: body.value || null, currency: body.currency || "GHS", expectedCloseDate: body.expectedCloseDate ? new Date(body.expectedCloseDate) : null, actualCloseDate: null, source: body.source || null, productInterest: body.productInterest || null, nextAction: body.nextAction || null, nextActionDate: body.nextActionDate ? new Date(body.nextActionDate) : null, lossReason: null, createdAt: now, updatedAt: now }); return NextResponse.json({ success: true, id }, { status: 201 }); }
