import { NextResponse } from "next/server";
import { and, asc, desc, eq, gte, lte, like, or } from "drizzle-orm";
import { db } from "@/db";
import { aiEmployees, businessUsers, crmDeals, crmPipelineStages, crmPipelines, customers } from "@/db/schema";
import { getCurrentMembership } from "@/lib/auth/tenant";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { createAuditLog } from "@/lib/auth/audit";
import { emitCrmEvent } from "@/lib/crm/events";
const MAX = 100;
const date = (v: string | null) => { if (!v) return null; const d = new Date(v); return Number.isNaN(d.getTime()) ? undefined : d; };
export async function GET(request: Request) {
 const membership = await getCurrentMembership(); if (!membership || !hasPermission(membership.role, membership.permissions, PERMISSIONS.CRM_VIEW)) return NextResponse.json({ error: "CRM access denied." }, { status: 403 });
 const p = new URL(request.url).searchParams; const conditions = [eq(crmDeals.businessId, membership.businessId)];
 const q = p.get("q")?.trim(); if (q) conditions.push(or(like(crmDeals.title, `%${q}%`), like(crmDeals.description, `%${q}%`), like(crmDeals.productInterest, `%${q}%`), like(customers.name, `%${q}%`), like(customers.email, `%${q}%`))!);
 for (const key of ["status","pipelineId","stageId","customerId","leadId","source","assignedUserId","assignedEmployeeId"] as const) { const value = p.get(key); if (value) conditions.push(eq(crmDeals[key], value)); }
 const pipelineId = p.get("pipelineId"); const stageId = p.get("stageId"); if (pipelineId) { const row = (await db.select({ id: crmPipelines.id }).from(crmPipelines).where(and(eq(crmPipelines.id, pipelineId), eq(crmPipelines.businessId, membership.businessId))).limit(1))[0]; if (!row) return NextResponse.json({ error: "Invalid pipeline." }, { status: 400 }); }
 if (stageId) { const row = (await db.select({ id: crmPipelineStages.id }).from(crmPipelineStages).where(and(eq(crmPipelineStages.id, stageId), eq(crmPipelineStages.businessId, membership.businessId), pipelineId ? eq(crmPipelineStages.pipelineId, pipelineId) : undefined)).limit(1))[0]; if (!row) return NextResponse.json({ error: "Invalid stage." }, { status: 400 }); }
 for (const key of ["assignedUserId","assignedEmployeeId"] as const) { const value = p.get(key); if (!value) continue; const table = key === "assignedUserId" ? businessUsers : aiEmployees; const row = (await db.select({ id: table.id }).from(table).where(and(eq(table.id, value), eq(table.businessId, membership.businessId))).limit(1))[0]; if (!row) return NextResponse.json({ error: `Invalid ${key}.` }, { status: 400 }); }
 for (const [key, column] of [["expectedCloseFrom", crmDeals.expectedCloseDate],["expectedCloseTo", crmDeals.expectedCloseDate],["createdFrom", crmDeals.createdAt],["createdTo", crmDeals.createdAt]] as const) { const d = date(p.get(key)); if (d === undefined) return NextResponse.json({ error: `Invalid ${key}.` }, { status: 400 }); if (d) conditions.push(key.endsWith("From") ? gte(column, d) : lte(column, d)); }
 const min = p.get("minValue"); const max = p.get("maxValue"); const minN = min === null ? null : Number(min); const maxN = max === null ? null : Number(max); if ((min !== null && (!Number.isFinite(Number(minN)) || Number(minN) < 0)) || (max !== null && (!Number.isFinite(Number(maxN)) || Number(maxN) < 0)) || (minN !== null && maxN !== null && minN > maxN)) return NextResponse.json({ error: "Invalid value range." }, { status: 400 });
 const sort = p.get("sort") || "updatedAt"; const direction = p.get("direction") || "desc"; const columns = { updatedAt: crmDeals.updatedAt, createdAt: crmDeals.createdAt, expectedCloseDate: crmDeals.expectedCloseDate, value: crmDeals.value, title: crmDeals.title } as const; if (!(sort in columns) || !["asc","desc"].includes(direction)) return NextResponse.json({ error: "Invalid sort." }, { status: 400 });
 const limit = Math.min(Math.max(Number(p.get("limit") || 50) || 50, 1), MAX); const rows = await db.select({ deal: crmDeals, pipeline: crmPipelines, stage: crmPipelineStages, customer: customers }).from(crmDeals).innerJoin(crmPipelines, and(eq(crmPipelines.id, crmDeals.pipelineId), eq(crmPipelines.businessId, membership.businessId))).innerJoin(crmPipelineStages, and(eq(crmPipelineStages.id, crmDeals.stageId), eq(crmPipelineStages.businessId, membership.businessId))).leftJoin(customers, and(eq(customers.id, crmDeals.customerId), eq(customers.businessId, membership.businessId))).where(and(...conditions)).orderBy(direction === "asc" ? asc(columns[sort as keyof typeof columns]) : desc(columns[sort as keyof typeof columns])).limit(limit + 1);
 const hasMore = rows.length > limit; const deals = rows.slice(0, limit).map((row) => ({ ...row.deal, pipelineName: row.pipeline.name, stageName: row.stage.name, customerName: row.customer?.name || null })); return NextResponse.json({ deals, items: deals, pagination: { limit, hasMore }, filters: Object.fromEntries(p.entries()) });
}
export async function POST(request: Request) { const membership = await getCurrentMembership(); if (!membership || !hasPermission(membership.role, membership.permissions, PERMISSIONS.CRM_DEAL_MANAGE)) return NextResponse.json({ error: "CRM management denied." }, { status: 403 }); const body = await request.json(); const title = String(body.title || "").trim(); if (!title || !body.pipelineId || !body.stageId) return NextResponse.json({ error: "title, pipelineId, and stageId are required." }, { status: 400 }); const valid = await db.select({ pipelineId: crmPipelineStages.pipelineId }).from(crmPipelineStages).innerJoin(crmPipelines, and(eq(crmPipelines.id, crmPipelineStages.pipelineId), eq(crmPipelines.businessId, membership.businessId))).where(and(eq(crmPipelineStages.id, body.stageId), eq(crmPipelineStages.pipelineId, body.pipelineId), eq(crmPipelineStages.businessId, membership.businessId))).limit(1); if (!valid[0]) return NextResponse.json({ error: "Stage does not belong to this pipeline." }, { status: 400 }); const now = new Date(); const id = crypto.randomUUID(); await db.insert(crmDeals).values({ id, businessId: membership.businessId, customerId: body.customerId || null, leadId: body.leadId || null, title, description: body.description || null, pipelineId: body.pipelineId, stageId: body.stageId, assignedEmployeeId: body.assignedEmployeeId || null, assignedUserId: body.assignedUserId || null, status: body.status || "open", value: body.value || null, currency: body.currency || "GHS", expectedCloseDate: body.expectedCloseDate ? new Date(body.expectedCloseDate) : null, actualCloseDate: null, source: body.source || null, productInterest: body.productInterest || null, nextAction: body.nextAction || null, nextActionDate: body.nextActionDate ? new Date(body.nextActionDate) : null, lossReason: null, createdAt: now, updatedAt: now }); await createAuditLog({ businessId: membership.businessId, action: "crm.deal.created", resource: "crm_deal", resourceId: id, metadata: { dealId: id, pipelineId: body.pipelineId, stageId: body.stageId } }); await emitCrmEvent(membership.businessId, "crm.deal.created", { dealId: id, customerId: body.customerId || null, leadId: body.leadId || null, pipelineId: body.pipelineId, stageId: body.stageId, value: body.value || null, currency: body.currency || "GHS" }); return NextResponse.json({ success: true, id }, { status: 201 }); }
