import crypto from "crypto";
import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { integrations } from "@/db/schema";
import { encrypt, decrypt } from "@/lib/encryption";
import { createAuditLog } from "@/lib/auth/audit";
export { buildGoogleEvent, hasBusyConflict } from "./google-calendar-logic";
import { buildGoogleEvent } from "./google-calendar-logic";

export const GOOGLE_PROVIDER = "google_calendar";
export const GOOGLE_SCOPES = "https://www.googleapis.com/auth/calendar";

function secret() { return process.env.GOOGLE_OAUTH_STATE_SECRET || process.env.BETTER_AUTH_SECRET || ""; }
export function signState(value: string) { return `${value}.${crypto.createHmac("sha256", secret()).update(value).digest("hex")}`; }
export function verifyState(signed: string) { const [value, sig] = signed.split("."); if (!value || !sig || !secret()) return null; const expected = crypto.createHmac("sha256", secret()).update(value).digest("hex"); return crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected)) ? value : null; }
export function oauthConfig() { const clientId = process.env.GOOGLE_CLIENT_ID?.trim(); const clientSecret = process.env.GOOGLE_CLIENT_SECRET?.trim(); const redirectUri = process.env.GOOGLE_CALENDAR_REDIRECT_URI?.trim(); if (!clientId || !clientSecret || !redirectUri) throw new Error("Google Calendar OAuth is not configured."); return { clientId, clientSecret, redirectUri }; }
export function parseCredentials(row: { credentialsEncrypted: string | null }) { return row.credentialsEncrypted ? JSON.parse(decrypt(row.credentialsEncrypted)) as { accessToken: string; refreshToken?: string; expiry: number; accountEmail?: string; scopes?: string } : null; }
export async function getConnection(businessId: string) { return (await db.select().from(integrations).where(and(eq(integrations.businessId, businessId), eq(integrations.provider, GOOGLE_PROVIDER))).limit(1))[0] || null; }
export async function saveConnection(businessId: string, credentials: Record<string, unknown>, metadata: Record<string, unknown>, status = "active") {
  const now = new Date(); const existing = await getConnection(businessId); const values = { businessId, provider: GOOGLE_PROVIDER, status, externalAccountId: String(metadata.accountEmail || ""), displayName: String(metadata.calendarName || "Google Calendar"), credentialsEncrypted: encrypt(JSON.stringify(credentials)), metadata: JSON.stringify(metadata), updatedAt: now };
  if (existing) { await db.update(integrations).set(values).where(and(eq(integrations.id, existing.id), eq(integrations.businessId, businessId))); return existing.id; }
  const id = crypto.randomUUID(); await db.insert(integrations).values({ id, ...values, createdAt: now, lastWebhookAt: null }); return id;
}
export async function accessTokenFor(row: { id: string; credentialsEncrypted: string | null }) { const c = parseCredentials(row); if (!c) throw new Error("Google Calendar is not connected."); if (c.expiry > Date.now() + 60_000) return c.accessToken; if (!c.refreshToken) throw new Error("Google Calendar needs attention: refresh token is unavailable."); const cfg = oauthConfig(); const body = new URLSearchParams({ client_id: cfg.clientId, client_secret: cfg.clientSecret, refresh_token: c.refreshToken, grant_type: "refresh_token" }); const res = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body }); if (!res.ok) throw new Error("Google Calendar token refresh failed."); const token = await res.json() as { access_token: string; expires_in?: number; refresh_token?: string }; const next = { ...c, accessToken: token.access_token, refreshToken: token.refresh_token || c.refreshToken, expiry: Date.now() + (token.expires_in || 3600) * 1000 }; await db.update(integrations).set({ credentialsEncrypted: encrypt(JSON.stringify(next)), updatedAt: new Date() }).where(eq(integrations.id, row.id)); return next.accessToken; }

export async function markGoogleNeedsAttention(businessId: string, reason: string) { const row = await getConnection(businessId); if (!row) return; const metadata = row.metadata ? JSON.parse(row.metadata) : {}; metadata.lastFailureAt = new Date().toISOString(); metadata.failureReason = reason; await db.update(integrations).set({ status: "needs_attention", metadata: JSON.stringify(metadata), updatedAt: new Date() }).where(and(eq(integrations.id, row.id), eq(integrations.businessId, businessId))); }

export async function createGoogleEvent(businessId: string, appointment: { id: string; title: string; description?: string|null; startAt: Date; endAt: Date; timezone: string; location?: string|null }) {
  const row = await getConnection(businessId); const metadata = row?.metadata ? JSON.parse(row.metadata) : {}; if (!row || row.status !== "active" || !metadata.calendarId) return null;
  const token = await accessTokenFor(row); const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(metadata.calendarId)}/events`, { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(buildGoogleEvent(appointment)) }); if (!res.ok) { await createAuditLog({ businessId, action: "google_calendar.sync_failed", resource: "appointment", resourceId: appointment.id, metadata: { operation: "create", status: res.status } }); throw new Error("Google Calendar event creation failed."); } const event = await res.json() as { id?: string }; if (!event.id) throw new Error("Google Calendar returned no event ID."); await createAuditLog({ businessId, action: "google_calendar.event_created", resource: "appointment", resourceId: appointment.id, metadata: { calendarId: metadata.calendarId } }); return { eventId: event.id, calendarId: metadata.calendarId };
}

export async function googleBusyIntervals(businessId: string, timeMin: Date, timeMax: Date) {
  const row = await getConnection(businessId); const metadata = row?.metadata ? JSON.parse(row.metadata) : {}; if (!row || row.status !== "active" || !metadata.calendarId) return [];
  const token = await accessTokenFor(row); const res = await fetch("https://www.googleapis.com/calendar/v3/freeBusy", { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify({ timeMin: timeMin.toISOString(), timeMax: timeMax.toISOString(), items: [{ id: metadata.calendarId }] }) }); if (!res.ok) throw new Error("Google Calendar availability check failed."); const data = await res.json() as { calendars?: Record<string, { busy?: Array<{ start: string; end: string }> }> }; return data.calendars?.[metadata.calendarId]?.busy || [];
}

/** Optional tenant working-hours policy stored in integration metadata until a canonical business-hours table exists. */
export async function assertWithinConfiguredWorkingHours(businessId: string, startAt: Date, endAt: Date, timezone: string) {
  const row = await getConnection(businessId); const hours = row?.metadata ? JSON.parse(row.metadata).workingHours : null; if (!hours || typeof hours !== "object") return;
  const parts = new Intl.DateTimeFormat("en-US", { timeZone: timezone, weekday: "short", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(startAt); const endParts = new Intl.DateTimeFormat("en-US", { timeZone: timezone, hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(endAt); const day = parts.find((p) => p.type === "weekday")?.value || "Sun"; const mins = (p: Intl.DateTimeFormatPart[]) => Number(p.find((x) => x.type === "hour")?.value || 0) * 60 + Number(p.find((x) => x.type === "minute")?.value || 0); const start = mins(parts); const end = mins(endParts); const rule = hours[day] || hours.default; if (!rule || rule.closed) return; const [openH, openM] = String(rule.open || "00:00").split(":").map(Number); const [closeH, closeM] = String(rule.close || "23:59").split(":").map(Number); if (start < openH * 60 + openM || end > closeH * 60 + closeM) throw new Error("The selected time is outside the business working hours.");
}

type AppointmentShape = { id: string; title: string; description?: string|null; startAt: Date; endAt: Date; timezone: string; location?: string|null; externalEventId?: string|null; externalCalendarId?: string|null };
async function linked(businessId: string, a: AppointmentShape) { const row = await getConnection(businessId); if (!row || row.status !== "active" || !a.externalEventId || !a.externalCalendarId) return null; return { row, calendarId: a.externalCalendarId, token: await accessTokenFor(row) }; }
export async function updateGoogleEventForAppointment(businessId: string, appointment: AppointmentShape) { const target = await linked(businessId, appointment); if (!target) return { status: "not_connected" as const }; const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(target.calendarId)}/events/${encodeURIComponent(appointment.externalEventId!)}`, { method: "PATCH", headers: { authorization: `Bearer ${target.token}`, "content-type": "application/json" }, body: JSON.stringify({ summary: appointment.title, description: `${appointment.description || ""}\n\nSuperKuba appointment ${appointment.id}`, location: appointment.location || undefined, start: { dateTime: appointment.startAt.toISOString(), timeZone: appointment.timezone }, end: { dateTime: appointment.endAt.toISOString(), timeZone: appointment.timezone } }) }); if (res.status === 404) { await createAuditLog({ businessId, action: "google_calendar.reconciliation_required", resource: "appointment", resourceId: appointment.id, metadata: { operation: "update" } }); return { status: "needs_attention" as const }; } if (!res.ok) throw new Error("Google Calendar event update failed."); await createAuditLog({ businessId, action: "google_calendar.event_updated", resource: "appointment", resourceId: appointment.id, metadata: { calendarId: target.calendarId } }); return { status: "synced" as const }; }
export async function deleteGoogleEventForAppointment(businessId: string, appointment: AppointmentShape) { const target = await linked(businessId, appointment); if (!target) return { status: "not_connected" as const }; const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(target.calendarId)}/events/${encodeURIComponent(appointment.externalEventId!)}`, { method: "DELETE", headers: { authorization: `Bearer ${target.token}` } }); if (res.status !== 404 && !res.ok) throw new Error("Google Calendar event cancellation failed."); await createAuditLog({ businessId, action: "google_calendar.event_cancelled", resource: "appointment", resourceId: appointment.id, metadata: { calendarId: target.calendarId } }); return { status: "synced" as const }; }
