import { desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { db } from "@/db";
import { marketingPublishJobs } from "@/db/schema";
import { requireMarketingAccess } from "@/lib/marketing/context";

export async function GET() { const access = await requireMarketingAccess("view"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); return NextResponse.json({ jobs: await db.select().from(marketingPublishJobs).where(eq(marketingPublishJobs.businessId, access.businessId)).orderBy(desc(marketingPublishJobs.updatedAt)) }); }
export async function POST(request: Request) { const access = await requireMarketingAccess("manage"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const body = await request.json().catch(() => null); if (typeof body?.contentItemId !== "string" || typeof body?.channel !== "string") return NextResponse.json({ error: "contentItemId and channel are required." }, { status: 400 }); const now = new Date(); const job = { id: randomUUID(), businessId: access.businessId, campaignId: typeof body?.campaignId === "string" ? body.campaignId : null, contentItemId: body.contentItemId, contentVariantId: typeof body?.contentVariantId === "string" ? body.contentVariantId : null, socialAccountId: null, channel: body.channel, scheduledAt: body?.scheduledAt ? new Date(body.scheduledAt) : null, status: body?.scheduledAt ? "scheduled" : "queued", attemptCount: 0, idempotencyKey: typeof body?.idempotencyKey === "string" ? body.idempotencyKey : randomUUID(), providerPostId: null, publishedAt: null, failedAt: null, failureCode: "PUBLISHING_ADAPTER_UNAVAILABLE", failureMessageSafe: "This channel is not connected to a publishing provider.", metadata: null, createdAt: now, updatedAt: now }; await db.insert(marketingPublishJobs).values(job); return NextResponse.json({ job, execution: "blocked", code: "PUBLISHING_ADAPTER_UNAVAILABLE" }, { status: 201 }); }
