import crypto from "node:crypto";
import type { PlanId } from "./entitlements";

export type BillingStatus = "trialing" | "active" | "past_due" | "canceled" | "incomplete" | "paused" | "expired" | "enterprise_contract";
export type BillingSubscription = { provider?: "stripe" | "paystack"; providerCustomerId: string | null; providerSubscriptionId: string | null; providerEventId: string; plan: PlanId; status: BillingStatus; currentPeriodStart: Date | null; currentPeriodEnd: Date | null; cancelAtPeriodEnd: boolean; trialEnd: Date | null };
export type BillingCapabilities = { supportsHostedCheckout: boolean; supportsSubscriptions: boolean; supportsBillingPortal: boolean; supportsPlanChange: boolean; supportsCancellation: boolean; supportsResume: boolean; supportsRecurringAuthorization: boolean };
export type BillingProvider = { name: "stripe" | "paystack"; capabilities: BillingCapabilities; createCheckoutSession: (input: { customerId?: string | null; priceId: string; successUrl: string; cancelUrl: string; metadata: Record<string, string> }) => Promise<{ id: string; url: string | null; customerId: string | null }>; createPortalSession: (customerId: string, returnUrl: string) => Promise<{ url: string }>; verifyTransaction?: (reference: string, expected: { email: string; businessId: string; plan: PlanId; amount: string; currency: string }) => Promise<BillingSubscription>; cancelSubscription?: (subscriptionId: string, customerReference?: string | null) => Promise<{ confirmed: boolean }>; changePlan?: (subscriptionId: string, planCode: string) => Promise<{ confirmed: boolean }>; parseWebhook: (payload: string, signature: string | null) => BillingSubscription | null };
const planPrice = { starter: "STRIPE_PRICE_STARTER", growth: "STRIPE_PRICE_GROWTH", pro: "STRIPE_PRICE_PRO" } as const;
const paystackPrice = { starter: "PAYSTACK_PLAN_STARTER", growth: "PAYSTACK_PLAN_GROWTH", pro: "PAYSTACK_PLAN_PRO" } as const;
export function activeBillingProvider() { const provider = process.env.BILLING_PROVIDER || "stripe"; if (provider !== "stripe" && provider !== "paystack") throw new Error("Unsupported BILLING_PROVIDER configuration."); return provider as "stripe" | "paystack"; }
export function getConfiguredPriceId(plan: PlanId) { if (plan === "enterprise") return null; const provider = activeBillingProvider(); return process.env[(provider === "stripe" ? planPrice : paystackPrice)[plan]] || null; }
function stripeRequest(path: string, options: RequestInit) { const secret = process.env.STRIPE_SECRET_KEY; if (!secret) throw new Error("STRIPE_SECRET_KEY is not configured."); return fetch(`https://api.stripe.com/v1/${path}`, { ...options, headers: { Authorization: `Bearer ${secret}`, "Content-Type": "application/x-www-form-urlencoded", ...options.headers } }); }
export const stripeProvider: BillingProvider = {
  name: "stripe", capabilities: { supportsHostedCheckout: true, supportsSubscriptions: true, supportsBillingPortal: true, supportsPlanChange: true, supportsCancellation: true, supportsResume: true, supportsRecurringAuthorization: true },
  async createCheckoutSession(input) { const form = new URLSearchParams({ mode: "subscription", "line_items[0][price]": input.priceId, "line_items[0][quantity]": "1", success_url: input.successUrl, cancel_url: input.cancelUrl, "metadata[businessId]": input.metadata.businessId, "metadata[plan]": input.metadata.plan }); if (input.customerId) form.set("customer", input.customerId); const response = await stripeRequest("checkout/sessions", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Stripe checkout could not be created."); return { id: data.id, url: data.url, customerId: data.customer || null }; },
  async createPortalSession(customerId, returnUrl) { const response = await stripeRequest("billing_portal/sessions", { method: "POST", body: new URLSearchParams({ customer: customerId, return_url: returnUrl }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Billing portal could not be opened."); return { url: data.url }; },
  parseWebhook(payload, signature) { const secret = process.env.STRIPE_WEBHOOK_SECRET; if (!secret || !signature) return null; const timestamp = signature.split(",").find((item) => item.startsWith("t="))?.slice(2); const hash = signature.split(",").find((item) => item.startsWith("v1="))?.slice(3); if (!timestamp || !hash) return null; const expected = crypto.createHmac("sha256", secret).update(`${timestamp}.${payload}`).digest("hex"); if (expected.length !== hash.length || !crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(hash))) return null; const event = JSON.parse(payload) as { id: string; type: string; data: { object: Record<string, unknown> } }; const object = event.data.object; const statusMap: Record<string, BillingStatus> = { active: "active", trialing: "trialing", past_due: "past_due", canceled: "canceled", incomplete: "incomplete", paused: "paused", unpaid: "expired" }; const eventStatus: Partial<Record<string, BillingStatus>> = { "checkout.session.completed": "active", "invoice.payment_succeeded": "active", "invoice.payment_failed": "past_due", "customer.subscription.trial_will_end": "trialing" }; const status = statusMap[String(object.status || "")] || eventStatus[event.type] || (event.type.includes("deleted") ? "canceled" : null); if (!status) return null; const metadata = (object.metadata || {}) as Record<string, string>; const price = (metadata.plan || "starter") as PlanId; const date = (value: unknown) => typeof value === "number" ? new Date(value * 1000) : null; return { providerCustomerId: typeof object.customer === "string" ? object.customer : null, providerSubscriptionId: typeof object.id === "string" && String(object.id).startsWith("sub_") ? object.id : typeof object.subscription === "string" ? object.subscription : null, providerEventId: event.id, plan: price, status, currentPeriodStart: date(object.current_period_start), currentPeriodEnd: date(object.current_period_end), cancelAtPeriodEnd: object.cancel_at_period_end === true, trialEnd: date(object.trial_end) }; },
};

export const paystackProvider: BillingProvider = {
  name: "paystack", capabilities: { supportsHostedCheckout: true, supportsSubscriptions: true, supportsBillingPortal: false, supportsPlanChange: false, supportsCancellation: true, supportsResume: false, supportsRecurringAuthorization: true },
  async createCheckoutSession(input) { const secret = process.env.PAYSTACK_SECRET_KEY; const amount = process.env[`PAYSTACK_AMOUNT_${input.metadata.plan.toUpperCase()}`]; const currency = process.env.SUPERKUBA_BILLING_CURRENCY || "GHS"; if (!secret || !amount || !input.metadata.email) throw new Error("Paystack billing provider is not configured."); const response = await fetch("https://api.paystack.co/transaction/initialize", { method: "POST", headers: { Authorization: `Bearer ${secret}`, "Content-Type": "application/json" }, body: JSON.stringify({ email: input.metadata.email, amount, currency, plan: input.priceId, callback_url: input.successUrl, metadata: input.metadata }) }); const data = await response.json(); if (!response.ok || !data.status) throw new Error(data.message || "Paystack checkout could not be created."); return { id: data.data.reference, url: data.data.authorization_url, customerId: data.data.customer?.customer_code || null }; },
  async verifyTransaction(reference, expected) { const secret = process.env.PAYSTACK_SECRET_KEY; if (!secret) throw new Error("Paystack billing provider is not configured."); const response = await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`, { headers: { Authorization: `Bearer ${secret}` } }); const data = await response.json(); const transaction = data.data; if (!response.ok || !data.status || transaction?.status !== "success" || transaction?.reference !== reference) throw new Error("Paystack transaction verification failed."); const metadata = transaction.metadata || {}; if (metadata.businessId !== expected.businessId || metadata.plan !== expected.plan || transaction.currency !== expected.currency || String(transaction.amount) !== expected.amount || String(transaction.customer?.email || "").toLowerCase() !== expected.email.toLowerCase()) throw new Error("Paystack transaction does not match the expected checkout."); return { provider: "paystack", providerCustomerId: transaction.customer?.customer_code || null, providerSubscriptionId: transaction.plan_object?.subscription_code || transaction.subscription_code || null, providerEventId: `verified:${reference}`, plan: expected.plan, status: "active", currentPeriodStart: null, currentPeriodEnd: null, cancelAtPeriodEnd: false, trialEnd: null }; },
  async cancelSubscription(subscriptionId) { const secret = process.env.PAYSTACK_SECRET_KEY; if (!secret) throw new Error("Paystack billing provider is not configured."); const authHeaders = { Authorization: `Bearer ${secret}`, "Content-Type": "application/json" }; const detailsResponse = await fetch(`https://api.paystack.co/subscription/${encodeURIComponent(subscriptionId)}`, { headers: authHeaders }); const details = await detailsResponse.json(); const emailToken = details.data?.email_token; if (!detailsResponse.ok || !emailToken) throw new Error("Paystack subscription cancellation token is unavailable."); const response = await fetch("https://api.paystack.co/subscription/disable", { method: "POST", headers: authHeaders, body: JSON.stringify({ code: subscriptionId, token: emailToken }) }); const data = await response.json(); if (!response.ok || !data.status) throw new Error(data.message || "Paystack subscription cancellation failed."); return { confirmed: true }; },
  async createPortalSession() { throw new Error("Paystack does not provide a hosted billing portal in this integration."); },
  parseWebhook(payload, signature) { if (!process.env.PAYSTACK_SECRET_KEY || signature !== crypto.createHmac("sha512", process.env.PAYSTACK_SECRET_KEY).update(payload).digest("hex")) return null; const event = JSON.parse(payload) as { event: string; data: Record<string, unknown> }; const status: BillingStatus = event.event === "charge.success" ? "active" : event.event.includes("failed") ? "past_due" : event.event.includes("disable") ? "canceled" : "incomplete"; const metadata = (event.data.metadata || {}) as Record<string, string>; return { providerCustomerId: typeof event.data.customer === "string" ? event.data.customer : null, providerSubscriptionId: typeof event.data.subscription_code === "string" ? event.data.subscription_code : null, providerEventId: String(event.data.reference || crypto.randomUUID()), plan: (metadata.plan || "starter") as PlanId, status, currentPeriodStart: null, currentPeriodEnd: null, cancelAtPeriodEnd: false, trialEnd: null }; },
};

export function getBillingProvider(): BillingProvider { return activeBillingProvider() === "paystack" ? paystackProvider : stripeProvider; }
