"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Filter = "all" | "conversations" | "sales" | "tasks" | "appointments" | "ai";
type Entry = { id: string; type: string; category: string; occurredAt: string | Date; title: string; summary: string; relatedResource?: { type: string; id: string | null }; };
type Customer360 = { customer: { name: string | null; email: string | null; phone: string | null; source?: string | null; createdAt?: string | Date; updatedAt?: string | Date }; summary: { activeLeads: number; openDeals: number; openDealValue: number; openTasks: number; overdueTasks: number; nextAppointment: { title?: string; startAt?: string | Date } | null; lastActivityAt?: string | Date }; leads: unknown[]; deals: unknown[]; appointments: unknown[]; tasks: unknown[]; conversations: unknown[]; timeline: Entry[]; pagination: { nextCursor: string | null; hasMore: boolean } };
const filters: { label: string; value: Filter }[] = [{ label: "All", value: "all" }, { label: "Conversations", value: "conversations" }, { label: "Sales", value: "sales" }, { label: "Tasks", value: "tasks" }, { label: "Appointments", value: "appointments" }, { label: "AI Activity", value: "ai" }];
export default function Customer360Page({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState<string>(); const [filter, setFilter] = useState<Filter>("all"); const [data, setData] = useState<Customer360 | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { void params.then(({ id: value }) => setId(value)); }, [params]);
  useEffect(() => { if (!id) return; void fetch(`/api/crm/customers/${id}?filter=${filter}&limit=50`, { cache: "no-store" }).then((r) => r.json()).then((value: Customer360) => setData(value)).finally(() => setLoading(false)); }, [id, filter]);
  if (loading && !data) return <main className="p-8 text-white">Loading customer…</main>;
  if (!data) return <main className="p-8 text-white">Customer not found.</main>;
  const customer = data.customer; const summary = data.summary;
  return <main className="min-h-screen bg-[#050507] px-6 py-10 text-white"><div className="mx-auto max-w-6xl">
    <Link href="/dashboard/crm" className="text-sm text-white/50 hover:text-white">← CRM</Link>
    <header className="mt-5 rounded-3xl border border-white/10 bg-white/[0.03] p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-white/40">Customer 360</p><h1 className="mt-2 text-4xl font-black">{customer.name || customer.email || "Customer"}</h1><p className="mt-2 text-white/60">{customer.email || "No email"}{customer.phone ? ` · ${customer.phone}` : ""}</p></div><div className="text-right text-sm text-white/50"><p>Source: {customer.source || "Unknown"}</p><p>Created: {formatDate(customer.createdAt)}</p><p>Last activity: {formatDate(summary.lastActivityAt)}</p></div></div></header>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Open deals" value={summary.openDeals} detail={summary.openDealValue ? `GHS ${summary.openDealValue.toLocaleString()}` : "No open value"} /><Card label="Active leads" value={summary.activeLeads} /><Card label="Open tasks" value={summary.openTasks} detail={summary.overdueTasks ? `${summary.overdueTasks} overdue` : "On track"} /><Card label="Next appointment" value={summary.nextAppointment ? formatDate(summary.nextAppointment.startAt) : "None"} detail={summary.nextAppointment?.title} /></div>
    {(summary.overdueTasks || summary.nextAppointment) && <section className="mt-6 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5"><h2 className="font-bold">Needs attention</h2><p className="mt-2 text-sm text-white/60">{summary.overdueTasks ? `${summary.overdueTasks} overdue task${summary.overdueTasks > 1 ? "s" : ""}. ` : ""}{summary.nextAppointment ? `Next appointment: ${summary.nextAppointment.title || "scheduled"}.` : ""}</p></section>}
    <section className="mt-8"><div className="flex flex-wrap gap-2">{filters.map((item) => <button key={item.value} onClick={() => setFilter(item.value)} className={`rounded-full px-4 py-2 text-sm ${filter === item.value ? "bg-white text-black" : "bg-white/10 text-white/70 hover:bg-white/15"}`}>{item.label}</button>)}</div><div className="mt-5 rounded-2xl border border-white/10 p-5"><h2 className="font-bold">Timeline</h2>{data.timeline.length ? <div className="mt-4 space-y-4">{data.timeline.map((entry) => <article key={entry.id} className="border-l border-white/15 pl-4"><p className="text-xs text-white/40">{formatDate(entry.occurredAt)} · {entry.category}</p><p className="mt-1 font-semibold">{entry.relatedResource?.type === "deal" && entry.relatedResource.id ? <Link className="hover:underline" href={`/dashboard/crm/deals/${entry.relatedResource.id}`}>{entry.title}</Link> : entry.title}</p><p className="text-sm text-white/60">{entry.summary}</p></article>)}</div> : <p className="mt-4 text-sm text-white/50">No activity for this filter.</p>}{data.pagination.hasMore && <p className="mt-5 text-xs text-white/40">More activity available; use the API cursor to continue.</p>}</div></section>
    <div className="mt-8 grid gap-6 md:grid-cols-2"><List title="Deals" items={data.deals} render={(item) => <>{String((item as Record<string, unknown>).title || "Deal")} · {String((item as Record<string, unknown>).status || "")}</>} /><List title="Conversations" items={data.conversations} render={(item) => <>{String((item as Record<string, unknown>).status || "")} · {String((item as Record<string, unknown>).integrationId || "")}</>} /><List title="Tasks" items={data.tasks} render={(item) => <>{String((item as Record<string, unknown>).title || "Deal")} · {String((item as Record<string, unknown>).status || "")}</>} /><List title="Appointments" items={data.appointments} render={(item) => <>{String((item as Record<string, unknown>).title || "Deal")} · {String((item as Record<string, unknown>).status || "")}</>} /></div>
  </div></main>;
}
function Card({ label, value, detail }: { label: string; value: string | number; detail?: string }) { return <article className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-xs uppercase tracking-wide text-white/40">{label}</p><p className="mt-3 text-2xl font-black">{value}</p>{detail && <p className="mt-1 text-xs text-white/50">{detail}</p>}</article>; }
function List({ title, items, render }: { title: string; items: unknown[]; render: (item: unknown) => React.ReactNode }) { return <section className="rounded-2xl border border-white/10 p-5"><h2 className="font-bold">{title}</h2><div className="mt-3 space-y-2 text-sm text-white/65">{items.slice(0, 5).map((item, index) => <p key={index}>{render(item)}</p>)}{!items.length && <p className="text-white/40">None recorded.</p>}</div></section>; }
function formatDate(value?: string | Date | null) { return value ? new Date(value).toLocaleString() : "Unknown"; }
