"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Ticket = { id: string; ticketReference: string; subject: string; description: string; conversationId: string | null; customerId: string | null; status: string; priority: string; resolutionSummary: string | null; openedAt: string; updatedAt: string };

export default function TicketDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [ticket, setTicket] = useState<Ticket | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void params.then(({ id }) => fetch(`/api/tickets/${encodeURIComponent(id)}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load ticket."); setTicket(data.ticket); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load ticket."))); }, [params]);
  if (error || !ticket) return <main className="min-h-screen bg-[#050507] px-6 py-12 text-white"><div className="mx-auto max-w-4xl">{error ? <p className="text-red-200">{error}</p> : <p className="text-white/40">Loading ticket...</p>}</div></main>;
  return <main className="min-h-screen bg-[#050507] px-4 py-8 text-white sm:px-6 lg:px-10 lg:py-12"><div className="mx-auto max-w-4xl"><Link href="/dashboard/tickets" className="text-sm text-cyan-300">Tickets</Link><header className="mt-6 flex flex-col justify-between gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-300/70">{ticket.ticketReference}</p><h1 className="mt-2 text-3xl font-black">{ticket.subject}</h1><p className="mt-2 text-sm text-white/40">Opened {new Date(ticket.openedAt).toLocaleString()}</p></div><div className="flex gap-2"><span className="rounded-full border border-white/10 px-3 py-1 text-xs uppercase text-white/60">{ticket.status}</span><span className="rounded-full border border-amber-300/20 px-3 py-1 text-xs uppercase text-amber-200">{ticket.priority}</span></div></header><section className="mt-8 space-y-6"><div><p className="text-xs font-bold uppercase tracking-wider text-white/30">Issue</p><p className="mt-3 whitespace-pre-wrap text-base leading-7 text-white/70">{ticket.description}</p></div>{ticket.resolutionSummary && <div className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.04] p-5"><p className="text-xs font-bold uppercase tracking-wider text-emerald-300/70">Resolution</p><p className="mt-2 text-sm leading-6 text-white/70">{ticket.resolutionSummary}</p></div>}<div className="flex flex-wrap gap-4 text-sm">{ticket.customerId && <Link href={`/dashboard/customers/${ticket.customerId}`} className="text-cyan-300">Open customer</Link>}{ticket.conversationId && <Link href={`/dashboard/inbox?conversation=${encodeURIComponent(ticket.conversationId)}`} className="text-cyan-300">Open conversation</Link>}</div></section></div></main>;
}
