import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { db } from "@/db";
import { marketingContentItems, marketingContentVariants } from "@/db/schema";
import { MARKETING_CHANNELS, requireMarketingAccess } from "@/lib/marketing/context";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { const access = await requireMarketingAccess("view"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const { id } = await params; const [item] = await db.select({ id: marketingContentItems.id }).from(marketingContentItems).where(and(eq(marketingContentItems.id, id), eq(marketingContentItems.businessId, access.businessId))); if (!item) return NextResponse.json({ error: "Content not found." }, { status: 404 }); return NextResponse.json({ variants: await db.select().from(marketingContentVariants).where(and(eq(marketingContentVariants.contentItemId, id), eq(marketingContentVariants.businessId, access.businessId))) }); }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const access = await requireMarketingAccess("manage"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const { id } = await params; const body = await request.json().catch(() => null); const channel = typeof body?.channel === "string" ? body.channel : "other"; if (!MARKETING_CHANNELS.includes(channel as never)) return NextResponse.json({ error: "Unsupported channel." }, { status: 400 }); const text = typeof body?.text === "string" ? body.text.trim() : ""; if (!text) return NextResponse.json({ error: "Variant text is required." }, { status: 400 }); const now = new Date(); const variant = { id: randomUUID(), businessId: access.businessId, contentItemId: id, channel, headline: typeof body?.headline === "string" ? body.headline : null, text, description: typeof body?.description === "string" ? body.description : null, callToAction: typeof body?.callToAction === "string" ? body.callToAction : null, linkUrl: typeof body?.linkUrl === "string" ? body.linkUrl : null, hashtags: typeof body?.hashtags === "string" ? body.hashtags : null, scheduledAt: body?.scheduledAt ? new Date(body.scheduledAt) : null, status: "draft", metadata: null, createdAt: now, updatedAt: now }; await db.insert(marketingContentVariants).values(variant); return NextResponse.json({ variant }, { status: 201 }); }
