import { desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { db } from "@/db";
import { marketingCampaigns } from "@/db/schema";
import { requireMarketingAccess } from "@/lib/marketing/context";

export async function GET() { const access = await requireMarketingAccess("view"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const campaigns = await db.select().from(marketingCampaigns).where(eq(marketingCampaigns.businessId, access.businessId)).orderBy(desc(marketingCampaigns.updatedAt)); return NextResponse.json({ campaigns }); }
export async function POST(request: Request) { const access = await requireMarketingAccess("manage"); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); const body = await request.json().catch(() => null); const name = typeof body?.name === "string" ? body.name.trim() : ""; if (!name) return NextResponse.json({ error: "Campaign name is required." }, { status: 400 }); const now = new Date(); const campaign = { id: randomUUID(), businessId: access.businessId, name, description: typeof body?.description === "string" ? body.description : null, objective: typeof body?.objective === "string" ? body.objective : "other", campaignType: typeof body?.campaignType === "string" ? body.campaignType : "organic", status: "draft", targetAudienceId: typeof body?.targetAudienceId === "string" ? body.targetAudienceId : null, offer: typeof body?.offer === "string" ? body.offer : null, landingUrl: typeof body?.landingUrl === "string" ? body.landingUrl : null, timezone: typeof body?.timezone === "string" ? body.timezone : null, startAt: body?.startAt ? new Date(body.startAt) : null, endAt: body?.endAt ? new Date(body.endAt) : null, budgetAmount: typeof body?.budgetAmount === "number" ? body.budgetAmount : null, budgetCurrency: typeof body?.budgetCurrency === "string" ? body.budgetCurrency : "USD", ownerUserId: null, ownerEmployeeId: null, approvalStatus: "draft", createdByUserId: null, createdByEmployeeId: null, metadata: null, createdAt: now, updatedAt: now }; await db.insert(marketingCampaigns).values(campaign); return NextResponse.json({ campaign }, { status: 201 }); }
