import { NextResponse } from "next/server";
import { headers } from "next/headers";
import crypto from "crypto";
import { and, eq } from "drizzle-orm";
import { auth } from "@/lib/auth";
import { getCurrentMembership } from "@/lib/auth/tenant";
import { hasPermission, PERMISSIONS } from "@/lib/auth/permissions";
import { getBusinessEntitlements, hasCapability } from "@/lib/billing/entitlements";
import { db } from "@/db";
import { integrations, appointments } from "@/db/schema";
import { getConnection, GOOGLE_SCOPES, markGoogleNeedsAttention, oauthConfig, signState, accessTokenFor } from "@/lib/google-calendar";
import { createAuditLog } from "@/lib/auth/audit";

async function context(manage = false) { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) return { response: NextResponse.json({ error: "Unauthorized" }, { status: 401 }) }; const membership = await getCurrentMembership(); if (!membership) return { response: NextResponse.json({ error: "Business access denied" }, { status: 403 }) }; const permission = manage ? PERMISSIONS.INTEGRATIONS_MANAGE : PERMISSIONS.INTEGRATIONS_VIEW; if (!hasPermission(membership.role, membership.permissions, permission)) return { response: NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; if (!hasCapability(await getBusinessEntitlements(membership.businessId), "integrations.calendar")) return { response: NextResponse.json({ error: "Calendar integration requires an eligible plan", code: "FEATURE_NOT_ENTITLED" }, { status: 403 }) }; return { membership, session } as const; }

export async function GET() { const c = await context(); if ("response" in c) return c.response; const row = await getConnection(c.membership.businessId); if (!row) return NextResponse.json({ connected: false, status: "disconnected" }); const metadata = row.metadata ? JSON.parse(row.metadata) : {}; return NextResponse.json({ connected: row.status === "active", status: row.status, accountEmail: metadata.accountEmail || row.externalAccountId, calendarId: metadata.calendarId || row.externalPhoneNumberId, calendarName: metadata.calendarName || row.displayName, lastSyncAt: metadata.lastSyncAt || null, scopes: metadata.scopes || GOOGLE_SCOPES }); }

export async function POST(request: Request) { const c = await context(true); if ("response" in c) return c.response; const action = (await request.json().catch(() => ({}))).action || "connect"; if (action === "connect") { const cfg = oauthConfig(); const payload = Buffer.from(JSON.stringify({ businessId: c.membership.businessId, userId: c.session.user.id, nonce: crypto.randomUUID(), exp: Date.now() + 10 * 60_000 })).toString("base64url"); const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.searchParams.set("client_id", cfg.clientId); url.searchParams.set("redirect_uri", cfg.redirectUri); url.searchParams.set("response_type", "code"); url.searchParams.set("access_type", "offline"); url.searchParams.set("prompt", "consent"); url.searchParams.set("scope", GOOGLE_SCOPES); url.searchParams.set("state", signState(payload)); return NextResponse.json({ url: url.toString() }); }
  if (action === "disconnect") { const row = await getConnection(c.membership.businessId); if (row) { await db.update(integrations).set({ status: "disconnected", updatedAt: new Date() }).where(and(eq(integrations.id, row.id), eq(integrations.businessId, c.membership.businessId))); await createAuditLog({ businessId: c.membership.businessId, userId: c.session.user.id, action: "google_calendar.disconnected", resource: "integration", resourceId: row.id }); } return NextResponse.json({ success: true }); }
  if (action === "calendars") { const row = await getConnection(c.membership.businessId); if (!row) return NextResponse.json({ error: "Not connected" }, { status: 409 }); const token = await accessTokenFor(row); const res = await fetch("https://www.googleapis.com/calendar/v3/users/me/calendarList", { headers: { authorization: `Bearer ${token}` } }); if (!res.ok) return NextResponse.json({ error: "Unable to list Google Calendars" }, { status: res.status === 401 ? 401 : 502 }); return NextResponse.json({ calendars: (await res.json() as { items?: Array<{ id: string; summary: string; accessRole?: string; primary?: boolean }> }).items || [] }); }
  if (action === "test_connection" || action === "sync_now") { const row = await getConnection(c.membership.businessId); if (!row) return NextResponse.json({ error: "Not connected" }, { status: 409 }); try { const token = await accessTokenFor(row); const metadata = row.metadata ? JSON.parse(row.metadata) : {}; if (!metadata.calendarId) return NextResponse.json({ error: "Select a calendar first" }, { status: 409 }); const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(metadata.calendarId)}`, { headers: { authorization: `Bearer ${token}` } }); if (!res.ok) throw new Error("Google Calendar connection check failed."); metadata.lastSyncAt = new Date().toISOString(); delete metadata.failureReason; await db.update(integrations).set({ status: "active", metadata: JSON.stringify(metadata), updatedAt: new Date() }).where(eq(integrations.id, row.id)); return NextResponse.json({ success: true, status: "synced", linkedAppointments: action === "sync_now" ? (await db.select({ id: appointments.id }).from(appointments).where(and(eq(appointments.businessId, c.membership.businessId), eq(appointments.externalProvider, "google_calendar")))).length : undefined }); } catch { await markGoogleNeedsAttention(c.membership.businessId, "provider_check_failed"); return NextResponse.json({ error: "Google Calendar needs attention" }, { status: 502 }); } }
  if (action === "select") { const body = await request.json(); const row = await getConnection(c.membership.businessId); if (!row) return NextResponse.json({ error: "Not connected" }, { status: 409 }); const metadata = row.metadata ? JSON.parse(row.metadata) : {}; metadata.calendarId = String(body.calendarId || ""); metadata.calendarName = String(body.calendarName || ""); await db.update(integrations).set({ metadata: JSON.stringify(metadata), displayName: metadata.calendarName, updatedAt: new Date() }).where(eq(integrations.id, row.id)); await createAuditLog({ businessId: c.membership.businessId, userId: c.session.user.id, action: "google_calendar.calendar_selected", resource: "integration", resourceId: row.id, metadata: { calendarId: metadata.calendarId, calendarName: metadata.calendarName } }); return NextResponse.json({ success: true }); }
  return NextResponse.json({ error: "Unsupported action" }, { status: 400 }); }

export async function PUT(request: Request) { return POST(request); }
export async function DELETE() { const c = await context(true); if ("response" in c) return c.response; const row = await getConnection(c.membership.businessId); if (row) await db.update(integrations).set({ status: "disconnected", updatedAt: new Date() }).where(and(eq(integrations.id, row.id), eq(integrations.businessId, c.membership.businessId))); return NextResponse.json({ success: true }); }
